Vagrant.configure("2") do |config|
  config.vm.define "vmlab01" do |vmlab01|
    vmlab01.vm.box = "ubuntu/jammy64"
    vmlab01.vm.hostname = 'srv-vmlab01'
    vmlab01.vm.network "public_network", ip: "10.47.11.215", bridge: "Realtek USB GbE Family Controller"
    vmlab01.vm.provision "shell",
      path: "script.sh"
  config.vm.provider "virtualbox" do |vmlab01|
    vmlab01.memory = "4096"
    vmlab01.cpus   = "2"
  end
 end
end
